In [2]:
df=pd.read_csv('/kaggle/input/job-placement-dataset/Job_Placement_Data.csv')
df.head()

,gender,ssc_percentage,ssc_board,hsc_percentage,hsc_board,hsc_subject,degree_percentage,undergrad_degree,work_experience,emp_test_percentage,specialisation,mba_percent,status
0,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed
1,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed
2,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed
3,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed
4,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed

In [3]:
df.shape

(215, 13)

In [4]:
df.isnull()

,gender,ssc_percentage,ssc_board,hsc_percentage,hsc_board,hsc_subject,degree_percentage,undergrad_degree,work_experience,emp_test_percentage,specialisation,mba_percent,status
0,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,False,False,False,False,False,False,False,False,False,False,False,False,False
211,False,False,False,False,False,False,False,False,False,False,False,False,False
212,False,False,False,False,False,False,False,False,False,False,False,False,False
213,False,False,False,False,False,False,False,False,False,False,False,False,False
214,False,False,False,False,False,False,False,False,False,False,False,False,False

In [5]:
df.isnull().sum()

gender                 0
ssc_percentage         0
ssc_board              0
hsc_percentage         0
hsc_board              0
hsc_subject            0
degree_percentage      0
undergrad_degree       0
work_experience        0
emp_test_percentage    0
specialisation         0
mba_percent            0
status                 0
dtype: int64

In [6]:
df['gender'].unique()

array(['M', 'F'], dtype=object)

In [7]:
df['gender'] = df['gender'].replace(['M','F'],[0,1])
df

/tmp/ipykernel_33/2424148781.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['gender'] = df['gender'].replace(['M','F'],[0,1])

,gender,ssc_percentage,ssc_board,hsc_percentage,hsc_board,hsc_subject,degree_percentage,undergrad_degree,work_experience,emp_test_percentage,specialisation,mba_percent,status
0,0,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed
1,0,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed
2,0,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed
3,0,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed
4,0,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed
...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,0,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.0,Mkt&Fin,74.49,Placed
211,0,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed
212,0,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.0,Mkt&Fin,69.72,Placed
213,1,74.00,Others,66.00,Others,Commerce,58.00,Comm&Mgmt,No,70.0,Mkt&HR,60.23,Placed
214,0,62.00,Central,58.00,Others,Science,53.00,Comm&Mgmt,No,89.0,Mkt&HR,60.22,Not Placed

In [8]:
df['specialisation'].unique()

array(['Mkt&HR', 'Mkt&Fin'], dtype=object)

In [9]:
df['specialisation'] = df['specialisation'].replace(['Mkt&HR','Mkt&Fin'],[0,1])
df

/tmp/ipykernel_33/238048750.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['specialisation'] = df['specialisation'].replace(['Mkt&HR','Mkt&Fin'],[0,1])

,gender,ssc_percentage,ssc_board,hsc_percentage,hsc_board,hsc_subject,degree_percentage,undergrad_degree,work_experience,emp_test_percentage,specialisation,mba_percent,status
0,0,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,0,58.80,Placed
1,0,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,1,66.28,Placed
2,0,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,1,57.80,Placed
3,0,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,0,59.43,Not Placed
4,0,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,1,55.50,Placed
...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,0,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.0,1,74.49,Placed
211,0,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,1,53.62,Placed
212,0,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.0,1,69.72,Placed
213,1,74.00,Others,66.00,Others,Commerce,58.00,Comm&Mgmt,No,70.0,0,60.23,Placed
214,0,62.00,Central,58.00,Others,Science,53.00,Comm&Mgmt,No,89.0,0,60.22,Not Placed

In [10]:
df['status'].unique()

array(['Placed', 'Not Placed'], dtype=object)

In [11]:
df['status'] = df['status'].replace(['Not Placed','Placed'],[0,1])
df

/tmp/ipykernel_33/2640962256.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['status'] = df['status'].replace(['Not Placed','Placed'],[0,1])

,gender,ssc_percentage,ssc_board,hsc_percentage,hsc_board,hsc_subject,degree_percentage,undergrad_degree,work_experience,emp_test_percentage,specialisation,mba_percent,status
0,0,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,0,58.80,1
1,0,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,1,66.28,1
2,0,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,1,57.80,1
3,0,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,0,59.43,0
4,0,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,1,55.50,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,0,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.0,1,74.49,1
211,0,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,1,53.62,1
212,0,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.0,1,69.72,1
213,1,74.00,Others,66.00,Others,Commerce,58.00,Comm&Mgmt,No,70.0,0,60.23,1
214,0,62.00,Central,58.00,Others,Science,53.00,Comm&Mgmt,No,89.0,0,60.22,0

In [12]:
df['work_experience'].unique()

array(['No', 'Yes'], dtype=object)

In [13]:
df['work_experience'] = df['work_experience'].replace(['No','Yes'],[0,1])
df

/tmp/ipykernel_33/3170183166.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['work_experience'] = df['work_experience'].replace(['No','Yes'],[0,1])

,gender,ssc_percentage,ssc_board,hsc_percentage,hsc_board,hsc_subject,degree_percentage,undergrad_degree,work_experience,emp_test_percentage,specialisation,mba_percent,status
0,0,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,0,55.0,0,58.80,1
1,0,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,1,86.5,1,66.28,1
2,0,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,0,75.0,1,57.80,1
3,0,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,0,66.0,0,59.43,0
4,0,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,0,96.8,1,55.50,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,0,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,0,91.0,1,74.49,1
211,0,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,0,74.0,1,53.62,1
212,0,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,1,59.0,1,69.72,1
213,1,74.00,Others,66.00,Others,Commerce,58.00,Comm&Mgmt,0,70.0,0,60.23,1
214,0,62.00,Central,58.00,Others,Science,53.00,Comm&Mgmt,0,89.0,0,60.22,0

In [14]:
col_to_drop = ['ssc_board','hsc_board']
col_to_drop

['ssc_board', 'hsc_board']

In [15]:
df.drop(columns = col_to_drop,inplace =True)
df

,gender,ssc_percentage,hsc_percentage,hsc_subject,degree_percentage,undergrad_degree,work_experience,emp_test_percentage,specialisation,mba_percent,status
0,0,67.00,91.00,Commerce,58.00,Sci&Tech,0,55.0,0,58.80,1
1,0,79.33,78.33,Science,77.48,Sci&Tech,1,86.5,1,66.28,1
2,0,65.00,68.00,Arts,64.00,Comm&Mgmt,0,75.0,1,57.80,1
3,0,56.00,52.00,Science,52.00,Sci&Tech,0,66.0,0,59.43,0
4,0,85.80,73.60,Commerce,73.30,Comm&Mgmt,0,96.8,1,55.50,1
...,...,...,...,...,...,...,...,...,...,...,...
210,0,80.60,82.00,Commerce,77.60,Comm&Mgmt,0,91.0,1,74.49,1
211,0,58.00,60.00,Science,72.00,Sci&Tech,0,74.0,1,53.62,1
212,0,67.00,67.00,Commerce,73.00,Comm&Mgmt,1,59.0,1,69.72,1
213,1,74.00,66.00,Commerce,58.00,Comm&Mgmt,0,70.0,0,60.23,1
214,0,62.00,58.00,Science,53.00,Comm&Mgmt,0,89.0,0,60.22,0

In [16]:
df.drop(columns =['hsc_subject'],inplace =True)
df

,gender,ssc_percentage,hsc_percentage,degree_percentage,undergrad_degree,work_experience,emp_test_percentage,specialisation,mba_percent,status
0,0,67.00,91.00,58.00,Sci&Tech,0,55.0,0,58.80,1
1,0,79.33,78.33,77.48,Sci&Tech,1,86.5,1,66.28,1
2,0,65.00,68.00,64.00,Comm&Mgmt,0,75.0,1,57.80,1
3,0,56.00,52.00,52.00,Sci&Tech,0,66.0,0,59.43,0
4,0,85.80,73.60,73.30,Comm&Mgmt,0,96.8,1,55.50,1
...,...,...,...,...,...,...,...,...,...,...
210,0,80.60,82.00,77.60,Comm&Mgmt,0,91.0,1,74.49,1
211,0,58.00,60.00,72.00,Sci&Tech,0,74.0,1,53.62,1
212,0,67.00,67.00,73.00,Comm&Mgmt,1,59.0,1,69.72,1
213,1,74.00,66.00,58.00,Comm&Mgmt,0,70.0,0,60.23,1
214,0,62.00,58.00,53.00,Comm&Mgmt,0,89.0,0,60.22,0

In [17]:
df['undergrad_degree'].unique()

array(['Sci&Tech', 'Comm&Mgmt', 'Others'], dtype=object)

In [18]:
df['undergrad_degree'] = df['undergrad_degree'].replace(['Sci&Tech', 'Comm&Mgmt', 'Others'],[0,1,2])
df

/tmp/ipykernel_33/2700489412.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['undergrad_degree'] = df['undergrad_degree'].replace(['Sci&Tech', 'Comm&Mgmt', 'Others'],[0,1,2])

,gender,ssc_percentage,hsc_percentage,degree_percentage,undergrad_degree,work_experience,emp_test_percentage,specialisation,mba_percent,status
0,0,67.00,91.00,58.00,0,0,55.0,0,58.80,1
1,0,79.33,78.33,77.48,0,1,86.5,1,66.28,1
2,0,65.00,68.00,64.00,1,0,75.0,1,57.80,1
3,0,56.00,52.00,52.00,0,0,66.0,0,59.43,0
4,0,85.80,73.60,73.30,1,0,96.8,1,55.50,1
...,...,...,...,...,...,...,...,...,...,...
210,0,80.60,82.00,77.60,1,0,91.0,1,74.49,1
211,0,58.00,60.00,72.00,0,0,74.0,1,53.62,1
212,0,67.00,67.00,73.00,1,1,59.0,1,69.72,1
213,1,74.00,66.00,58.00,1,0,70.0,0,60.23,1
214,0,62.00,58.00,53.00,1,0,89.0,0,60.22,0

In [19]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [20]:
data_input =df.drop(columns=['status'])
data_output =df['status']

In [21]:
data_input.shape

(215, 9)

In [22]:
X_train, X_test, y_train, y_test = train_test_split(data_input,data_output, test_size=0.2)

In [23]:
X_train.shape

(172, 9)

In [24]:
model =LogisticRegression()

In [25]:
model.fit(X_train,y_train)

/opt/conda/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [26]:
model.score(X_test,y_test)

0.8604651162790697